version: '3'

services:
  vcenter:
    image: cblomart/vcsim
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 30s

  vsphere-graphite:
    image: cblomart/vsphere-graphite:9ebd547
    environment:
      - VCENTER_VCSIM=user:pass@vcenter:8989
      - CONFIG_TYPE=thinprometheus
      - CONFIG_HOSTNAME=*
      - CONFIG_PORT=9155
    ports:
      - "9155:9155"
    depends_on:
      - vcenter
      - graphite
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 3
        window: 120s
